# -*- coding: utf-8 -*-
"""Movie Recommendation System – MovieLens.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eu_DcFfa6_ASJnRhnm4HA490-PEr9OSR
"""

# ===============================
# Install + Setup + Load + Train
# ===============================

# -- install compatible numpy + scikit-surprise
!pip uninstall -y numpy -q
!pip install -q numpy==1.26.4
!pip install -q scikit-surprise pandas scikit-learn tqdm

# -- download dataset (MovieLens small)
!wget -q -O ml_latest_small.zip http://files.grouplens.org/datasets/movielens/ml-latest-small.zip
!unzip -q -o ml_latest_small.zip

# -- imports
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from surprise import Dataset, Reader, SVD
from surprise.model_selection import train_test_split

# -- load data
ratings = pd.read_csv('ml-latest-small/ratings.csv')
movies  = pd.read_csv('ml-latest-small/movies.csv')

print("ratings:", ratings.shape)
print("movies :", movies.shape)

# -- quick maps
movieid2title = dict(zip(movies.movieId, movies.title))
all_movie_ids = movies.movieId.unique().tolist()

# -- build user-item matrix for Item-CF
R = ratings.pivot_table(index='userId', columns='movieId', values='rating').fillna(0)
R_matrix = R.values
item_ids = R.columns.tolist()

# -- item similarity (cosine)
item_sim = cosine_similarity(R_matrix.T)
item_sim_df = pd.DataFrame(item_sim, index=item_ids, columns=item_ids)

def recommend_itemcf(user_id, N=10):
    if user_id not in R.index:
        return []
    user_ratings = R.loc[user_id]
    rated_items = user_ratings[user_ratings > 0].index.tolist()
    if len(rated_items) == 0:
        return []
    sim_sub = item_sim_df.loc[rated_items]
    weights = sim_sub.T.dot(user_ratings[rated_items].values)
    denom = sim_sub.abs().sum(axis=0).replace(0, np.nan)
    scores = weights / denom
    scores = scores.drop(labels=rated_items, errors='ignore')
    scores = scores.dropna()
    top = scores.sort_values(ascending=False).head(N)
    return [(int(mid), movieid2title[int(mid)], float(score)) for mid, score in top.items()]

# -- Surprise SVD model
reader = Reader(rating_scale=(0.5, 5.0))
data = Dataset.load_from_df(ratings[['userId','movieId','rating']], reader)
trainset, testset = train_test_split(data, test_size=0.2, random_state=42)

algo = SVD(n_factors=50, n_epochs=20, random_state=42)
algo.fit(trainset)

def recommend_svd(user_id, N=10):
    rated = set(ratings[ratings.userId==user_id].movieId.tolist())
    candidates = [mid for mid in all_movie_ids if mid not in rated]
    preds = []
    for mid in candidates:
        pred = algo.predict(user_id, mid)
        preds.append((mid, pred.est))
    preds.sort(key=lambda x: x[1], reverse=True)
    top = preds[:N]
    return [(int(mid), movieid2title[int(mid)], float(score)) for mid, score in top]

!pip install gradio

import gradio as gr

def get_recommendations(user_id, N, model):
    return recommend_movies(user_id, N, model=model)

iface = gr.Interface(
    fn=get_recommendations,
    inputs=[
        gr.Number(label="User ID"),
        gr.Number(label="Number of Recommendations"),
        gr.Dropdown(['svd', 'item'], label="Model")
    ],
    outputs=gr.Textbox(label="Recommended Movies")
)

iface.launch()

print(recommend_itemcf(1, 5))   # Item-based CF for user 1
print(recommend_svd(1, 5))      # SVD for user 1

# Step 5 — Unified wrapper for recommendations

def recommend_movies(user_id, N=10, model='svd'):
    """
    Return top-N recommended movies for a given user.
    model: 'svd' (matrix factorization) or 'item' (item-based CF)
    """
    if model == 'svd':
        return recommend_svd(user_id, N)
    elif model == 'item':
        return recommend_itemcf(user_id, N)
    else:
        raise ValueError("model must be 'svd' or 'item'")

# Example usage
print("SVD Recommendations for user 1:")
print(recommend_movies(1, N=5, model='svd'))
print("\nItem-CF Recommendations for user 1:")
print(recommend_movies(1, N=5, model='item'))

# Step 6 — Evaluation Metrics for SVD model
from collections import defaultdict
from math import log2
import numpy as np

# Get test predictions
predictions = algo.test(testset)

def precision_recall_at_k(predictions, k=10, threshold=4.0):
    """Compute avg Precision@K and Recall@K."""
    user_preds = defaultdict(list)
    for p in predictions:
        user_preds[p.uid].append((p.est, p.r_ui))
    precisions, recalls = [], []
    for uid, est_true in user_preds.items():
        est_true.sort(key=lambda x: x[0], reverse=True)
        topk = est_true[:k]
        n_rel = sum(1 for (_, true) in est_true if true >= threshold)
        n_rec_k = sum(1 for (_, true) in topk if true >= threshold)
        precisions.append(n_rec_k / k)
        recalls.append(n_rec_k / n_rel if n_rel > 0 else 0.0)
    return np.mean(precisions), np.mean(recalls)

def ndcg_at_k(predictions, k=10, threshold=4.0):
    """Compute avg NDCG@K."""
    user_preds = defaultdict(list)
    for p in predictions:
        user_preds[p.uid].append((p.est, p.r_ui))
    ndcgs = []
    for uid, est_true in user_preds.items():
        est_true.sort(key=lambda x: x[0], reverse=True)
        dcg = 0.0
        for i, (_, true) in enumerate(est_true[:k], start=1):
            rel = 1 if true >= threshold else 0
            dcg += (2**rel - 1) / log2(i + 1)
        ideal_rels = sorted([1 if t >= threshold else 0 for (_, t) in est_true], reverse=True)
        idcg = sum((2**rel - 1) / log2(i + 1) for i, rel in enumerate(ideal_rels[:k], start=1))
        ndcgs.append(dcg / idcg if idcg > 0 else 0.0)
    return np.mean(ndcgs)

# Compute metrics
prec, rec = precision_recall_at_k(predictions, k=10, threshold=4.0)
ndcg = ndcg_at_k(predictions, k=10, threshold=4.0)

print(f"SVD Evaluation Metrics:")
print(f"Precision@10: {prec:.4f}")
print(f"Recall@10:    {rec:.4f}")
print(f"NDCG@10:      {ndcg:.4f}")

# Step 6b — Evaluation for Item-CF

from collections import defaultdict
from math import log2

def predict_itemcf(user_id, movie_id, k_neighbors=20):
    """
    Predict rating for a given user and movie using Item-CF.
    Formula: weighted sum of user’s ratings on similar items.
    """
    if user_id not in R.index or movie_id not in item_sim_df.columns:
        return 0.0

    user_ratings = R.loc[user_id]
    rated_items = user_ratings[user_ratings > 0]
    if rated_items.empty:
        return 0.0

    # similarities between target movie and items the user rated
    sims = item_sim_df.loc[movie_id, rated_items.index]

    # top-k most similar items
    sims = sims.sort_values(ascending=False)[:k_neighbors]
    relevant_ratings = rated_items[sims.index]

    if sims.sum() == 0:
        return 0.0

    pred = np.dot(sims.values, relevant_ratings.values) / sims.abs().sum()
    return float(pred)

# Build predictions list like Surprise
itemcf_predictions = []
for (uid, mid, true_r) in testset:
    est = predict_itemcf(int(uid), int(mid))
    itemcf_predictions.append((uid, mid, true_r, est))

# Adapt evaluation functions
def precision_recall_at_k_itemcf(predictions, k=10, threshold=4.0):
    user_preds = defaultdict(list)
    for uid, mid, true_r, est in predictions:
        user_preds[uid].append((est, true_r))
    precisions, recalls = [], []
    for uid, est_true in user_preds.items():
        est_true.sort(key=lambda x: x[0], reverse=True)
        topk = est_true[:k]
        n_rel = sum(1 for (_, true) in est_true if true >= threshold)
        n_rec_k = sum(1 for (_, true) in topk if true >= threshold)
        precisions.append(n_rec_k / k)

# ===========================================
# Item-CF Evaluation Only
# ===========================================

from collections import defaultdict
from math import log2
import numpy as np

def predict_itemcf(user_id, movie_id, k_neighbors=20):
    """
    Predict rating for a given user and movie using Item-CF.
    Formula: weighted sum of user's ratings on similar items.
    """
    if user_id not in R.index or movie_id not in item_sim_df.columns:
        return 0.0

    user_ratings = R.loc[user_id]
    rated_items = user_ratings[user_ratings > 0]
    if rated_items.empty:
        return 0.0

    sims = item_sim_df.loc[movie_id, rated_items.index]
    sims = sims.sort_values(ascending=False)[:k_neighbors]
    relevant_ratings = rated_items[sims.index]

    if sims.sum() == 0:
        return 0.0

    pred = np.dot(sims.values, relevant_ratings.values) / sims.abs().sum()
    return float(pred)

# Build prediction list (like Surprise does)
itemcf_predictions = []
for (uid, mid, true_r) in testset:   # testset comes from Surprise split
    est = predict_itemcf(int(uid), int(mid))
    itemcf_predictions.append((uid, mid, true_r, est))

def precision_recall_at_k_itemcf(predictions, k=10, threshold=4.0):
    user_preds = defaultdict(list)
    for uid, mid, true_r, est in predictions:
        user_preds[uid].append((est, true_r))
    precisions, recalls = [], []
    for uid, est_true in user_preds.items():
        est_true.sort(key=lambda x: x[0], reverse=True)
        topk = est_true[:k]
        n_rel = sum(1 for (_, true) in est_true if true >= threshold)
        n_rec_k = sum(1 for (_, true) in topk if true >= threshold)
        precisions.append(n_rec_k / k)
        recalls.append(n_rec_k / n_rel if n_rel > 0 else 0.0)
    return np.mean(precisions), np.mean(recalls)

def ndcg_at_k_itemcf(predictions, k=10, threshold=4.0):
    user_preds = defaultdict(list)
    for uid, mid, true_r, est in predictions:
        user_preds[uid].append((est, true_r))
    ndcgs = []
    for uid, est_true in user_preds.items():
        est_true.sort(key=lambda x: x[0], reverse=True)
        dcg = 0.0
        for i, (_, true) in enumerate(est_true[:k], start=1):
            rel = 1 if true >= threshold else 0
            dcg += (2**rel - 1) / log2(i + 1)
        ideal_rels = sorted([1 if t >= threshold else 0 for (_, t) in est_true], reverse=True)
        idcg = sum((2**rel - 1) / log2(i + 1) for i, rel in enumerate(ideal_rels[:k], start=1))
        ndcgs.append(dcg / idcg if idcg > 0 else 0.0)
    return np.mean(ndcgs)

# Compute metrics
prec_item, rec_item = precision_recall_at_k_itemcf(itemcf_predictions, k=10, threshold=4.0)
ndcg_item = ndcg_at_k_itemcf(itemcf_predictions, k=10, threshold=4.0)

print("Item-CF Evaluation Metrics:")
print(f"Precision@10: {prec_item:.4f}")
print(f"Recall@10:    {rec_item:.4f}")
print(f"NDCG@10:      {ndcg_item:.4f}")

# ===========================================
# Evaluation: Compare SVD vs Item-CF
# ===========================================

from collections import defaultdict
from math import log2

# --- SVD metrics (we already have algo, trainset, testset, predictions from step 4/6)
predictions = algo.test(testset)

def precision_recall_at_k(predictions, k=10, threshold=4.0):
    user_preds = defaultdict(list)
    for p in predictions:
        user_preds[p.uid].append((p.est, p.r_ui))
    precisions, recalls = [], []
    for uid, est_true in user_preds.items():
        est_true.sort(key=lambda x: x[0], reverse=True)
        topk = est_true[:k]
        n_rel = sum(1 for (_, true) in est_true if true >= threshold)
        n_rec_k = sum(1 for (_, true) in topk if true >= threshold)
        precisions.append(n_rec_k / k)
        recalls.append(n_rec_k / n_rel if n_rel > 0 else 0.0)
    return np.mean(precisions), np.mean(recalls)

def ndcg_at_k(predictions, k=10, threshold=4.0):
    user_preds = defaultdict(list)
    for p in predictions:
        user_preds[p.uid].append((p.est, p.r_ui))
    ndcgs = []
    for uid, est_true in user_preds.items():
        est_true.sort(key=lambda x: x[0], reverse=True)
        dcg = 0.0
        for i, (_, true) in enumerate(est_true[:k], start=1):
            rel = 1 if true >= threshold else 0
            dcg += (2**rel - 1) / log2(i + 1)
        ideal_rels = sorted([1 if t >= threshold else 0 for (_, t) in est_true], reverse=True)
        idcg = sum((2**rel - 1) / log2(i + 1) for i, rel in enumerate(ideal_rels[:k], start=1))
        ndcgs.append(dcg / idcg if idcg > 0 else 0.0)
    return np.mean(ndcgs)

prec_svd, rec_svd = precision_recall_at_k(predictions, k=10, threshold=4.0)
ndcg_svd = ndcg_at_k(predictions, k=10, threshold=4.0)


# --- Item-CF metrics
def predict_itemcf(user_id, movie_id, k_neighbors=20):
    if user_id not in R.index or movie_id not in item_sim_df.columns:
        return 0.0
    user_ratings = R.loc[user_id]
    rated_items = user_ratings[user_ratings > 0]
    if rated_items.empty:
        return 0.0
    sims = item_sim_df.loc[movie_id, rated_items.index]
    sims = sims.sort_values(ascending=False)[:k_neighbors]
    relevant_ratings = rated_items[sims.index]
    if sims.sum() == 0:
        return 0.0
    pred = np.dot(sims.values, relevant_ratings.values) / sims.abs().sum()
    return float(pred)

itemcf_predictions = []
for (uid, mid, true_r) in testset:
    est = predict_itemcf(int(uid), int(mid))
    itemcf_predictions.append((uid, mid, true_r, est))

def precision_recall_at_k_itemcf(predictions, k=10, threshold=4.0):
    user_preds = defaultdict(list)
    for uid, mid, true_r, est in predictions:
        user_preds[uid].append((est, true_r))
    precisions, recalls = [], []
    for uid, est_true in user_preds.items():
        est_true.sort(key=lambda x: x[0], reverse=True)
        topk = est_true[:k]
        n_rel = sum(1 for (_, true) in est_true if true >= threshold)
        n_rec_k = sum(1 for (_, true) in topk if true >= threshold)
        precisions.append(n_rec_k / k)
        recalls.append(n_rec_k / n_rel if n_rel > 0 else 0.0)
    return np.mean(precisions), np.mean(recalls)

def ndcg_at_k_itemcf(predictions, k=10, threshold=4.0):
    user_preds = defaultdict(list)
    for uid, mid, true_r, est in predictions:
        user_preds[uid].append((est, true_r))
    ndcgs = []
    for uid, est_true in user_preds.items():
        est_true.sort(key=lambda x: x[0], reverse=True)
        dcg = 0.0
        for i, (_, true) in enumerate(est_true[:k], start=1):
            rel = 1 if true >= threshold else 0
            dcg += (2**rel - 1) / log2(i + 1)
        ideal_rels = sorted([1 if t >= threshold else 0 for (_, t) in est_true], reverse=True)
        idcg = sum((2**rel - 1) / log2(i + 1) for i, rel in enumerate(ideal_rels[:k], start=1))
        ndcgs.append(dcg / idcg if idcg > 0 else 0.0)
    return np.mean(ndcgs)

prec_item, rec_item = precision_recall_at_k_itemcf(itemcf_predictions, k=10, threshold=4.0)
ndcg_item = ndcg_at_k_itemcf(itemcf_predictions, k=10, threshold=4.0)


# --- Final comparison table
import pandas as pd

results = pd.DataFrame({
    "Model": ["SVD", "Item-CF"],
    "Precision@10": [prec_svd, prec_item],
    "Recall@10": [rec_svd, rec_item],
    "NDCG@10": [ndcg_svd, ndcg_item]
})

print(results.to_string(index=False))

import matplotlib.pyplot as plt

# Print values
print("Item-CF Metrics:")
print(f"Precision@10 = {prec_item:.4f}")
print(f"Recall@10    = {rec_item:.4f}")
print(f"NDCG@10      = {ndcg_item:.4f}")

# Bar chart for Item-CF
metrics = ["Precision@10", "Recall@10", "NDCG@10"]
values = [prec_item, rec_item, ndcg_item]

plt.figure(figsize=(6,4))
plt.bar(metrics, values)
plt.title("Item-CF Evaluation Metrics")
plt.ylabel("Score")
plt.ylim(0,1)
plt.show()

# Print values for both models
print("SVD Metrics:")
print(f"Precision@10 = {prec_svd:.4f}")
print(f"Recall@10    = {rec_svd:.4f}")
print(f"NDCG@10      = {ndcg_svd:.4f}")

print("\nItem-CF Metrics:")
print(f"Precision@10 = {prec_item:.4f}")
print(f"Recall@10    = {rec_item:.4f}")
print(f"NDCG@10      = {ndcg_item:.4f}")

# Bar chart comparison
metrics = ["Precision@10", "Recall@10", "NDCG@10"]
svd_values = [prec_svd, rec_svd, ndcg_svd]
itemcf_values = [prec_item, rec_item, ndcg_item]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(7,5))
plt.bar(x - width/2, svd_values, width, label='SVD')
plt.bar(x + width/2, itemcf_values, width, label='Item-CF')
plt.xticks(x, metrics)
plt.ylabel("Score")
plt.title("SVD vs Item-CF Evaluation Metrics")
plt.ylim(0,1)
plt.legend()
plt.show()

# Assume recommend_movies(user_id, N, model='svd') is already defined

# Ask user for input
user_id = int(input("Enter your User ID: "))
N = int(input("How many movies do you want to see? "))
model = input("Choose model ('svd' or 'item'): ").strip().lower()

# Get recommendations
try:
    recommended_movies = recommend_movies(user_id, N, model=model)
    print(f"\nTop {N} recommended movies for User {user_id} using {model.upper()} model:")
    for i, movie in enumerate(recommended_movies, 1):
        print(f"{i}. {movie}")
except Exception as e:
    print(f"Error: {e}")